"use client"

import { useState, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { FileText, Download, Loader2, Lock } from "lucide-react"
import { motion } from "framer-motion"

interface ReportData {
  group: {
    name: string
    description: string | null
    githubRepo: string | null
    createdAt: string
  }
  members: {
    name: string
    githubUsername: string | null
    role: string
    joinedAt: string
  }[]
  contributions: {
    name: string
    score: number
    commits: number
    additions: number
    deletions: number
  }[]
  commitStats: {
    total: number
    totalAdditions: number
    totalDeletions: number
  }
  aiAnalysis: string | null
  generatedAt: string
}

interface ReportGeneratorProps {
  groupId: string
  groupName: string
  hasData: boolean
  canViewReports: boolean
}

export function ReportGenerator({
  groupId,
  groupName,
  hasData,
  canViewReports,
}: ReportGeneratorProps) {
  const [report, setReport] = useState<ReportData | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const reportRef = useRef<HTMLDivElement>(null)

  const generateReport = async () => {
    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ groupId }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate report")
      }

      setReport(data.report)
    } catch (error) {
      setError(error instanceof Error ? error.message : "Failed to generate report")
    } finally {
      setIsLoading(false)
    }
  }

  const downloadReport = () => {
    if (!report) return

    const content = `
FAIRGROUP CONTRIBUTION REPORT
=============================
Generated: ${new Date(report.generatedAt).toLocaleString()}

PROJECT: ${report.group.name}
${report.group.description ? `Description: ${report.group.description}` : ""}
${report.group.githubRepo ? `Repository: ${report.group.githubRepo}` : ""}

TEAM MEMBERS (${report.members.length})
------------------
${report.members.map((m) => `- ${m.name} (${m.role})${m.githubUsername ? ` @${m.githubUsername}` : ""}`).join("\n")}

CONTRIBUTION SUMMARY
--------------------
Total Commits: ${report.commitStats.total}
Total Lines Changed: +${report.commitStats.totalAdditions} / -${report.commitStats.totalDeletions}

INDIVIDUAL CONTRIBUTIONS
------------------------
${report.contributions.map((c, i) => `${i + 1}. ${c.name}: ${c.score}%
   - Commits: ${c.commits}
   - Lines: +${c.additions} / -${c.deletions}`).join("\n\n")}

${report.aiAnalysis ? `
AI ANALYSIS
-----------
${report.aiAnalysis}
` : ""}

---
Report generated by FairGroup (https://fairgroup.app)
    `.trim()

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${groupName.replace(/\s+/g, "_")}_contribution_report.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (!canViewReports) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
      >
        <Card className="border-dashed border-primary/25 bg-muted/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Lock className="h-5 w-5 text-muted-foreground" />
              Contribution reports
            </CardTitle>
            <CardDescription>
              Only the instructor who created this group can generate and download official reports.
            </CardDescription>
          </CardHeader>
        </Card>
      </motion.div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
    >
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                Contribution Report
              </CardTitle>
              <CardDescription>
                Generate a detailed report for instructors
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={generateReport}
                disabled={isLoading || !hasData}
                variant={report ? "outline" : "default"}
                className="gap-2"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4" />
                    {report ? "Regenerate" : "Generate Report"}
                  </>
                )}
              </Button>
              {report && (
                <Button onClick={downloadReport} variant="gradient" className="gap-2">
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {!hasData && (
            <p className="text-muted-foreground">
              Sync your GitHub commits to generate a report.
            </p>
          )}
          {error && <p className="text-destructive">{error}</p>}
          {report && (
            <div ref={reportRef} className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Total Commits</p>
                  <p className="text-2xl font-bold text-foreground">{report.commitStats.total}</p>
                </div>
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Lines Added</p>
                  <p className="text-2xl font-bold text-green-600">+{report.commitStats.totalAdditions}</p>
                </div>
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Lines Removed</p>
                  <p className="text-2xl font-bold text-red-500">-{report.commitStats.totalDeletions}</p>
                </div>
              </div>

              <div>
                <h4 className="mb-3 font-semibold text-foreground">Contribution Breakdown</h4>
                <div className="space-y-2">
                  {report.contributions.map((c, index) => (
                    <div
                      key={index}
                      className="flex items-center justify-between rounded-lg border border-border p-3"
                    >
                      <div>
                        <p className="font-medium text-foreground">{c.name}</p>
                        <p className="text-sm text-muted-foreground">
                          {c.commits} commits · +{c.additions} / -{c.deletions}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-2xl font-bold text-primary">{c.score}%</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {report.aiAnalysis && (
                <div>
                  <h4 className="mb-3 font-semibold text-foreground">AI Analysis</h4>
                  <div className="rounded-lg border border-border bg-muted/30 p-4">
                    {report.aiAnalysis.split("\n").map((paragraph, index) => (
                      <p key={index} className="mb-2 text-sm text-foreground last:mb-0">
                        {paragraph}
                      </p>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </motion.div>
  )
}
